name: Background Jobs

on:
  schedule:
    # Job scanning every 4 hours
    - cron: '0 */4 * * *'
    # Cleanup every 6 hours  
    - cron: '0 */6 * * *'
    # Daily summary at 9 AM
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  determine-job-type:
    runs-on: ubuntu-latest
    outputs:
      job-type: ${{ steps.determine.outputs.job-type }}
    steps:
      - name: Determine job type
        id: determine
        run: |
          current_hour=$(date +%H)
          current_minute=$(date +%M)
          
          # Check if it's 9 AM (daily summary)
          if [[ "$current_hour" == "09" && "$current_minute" == "00" ]]; then
            echo "job-type=daily-summary" >> $GITHUB_OUTPUT
          # Check if it's a 6-hour interval (cleanup)  
          elif [[ $(($current_hour % 6)) == "0" && "$current_minute" == "00" ]]; then
            echo "job-type=cleanup" >> $GITHUB_OUTPUT
          # Default to job scanning (4-hour interval)
          else
            echo "job-type=job-scan" >> $GITHUB_OUTPUT
          fi

  job-scan:
    runs-on: ubuntu-latest
    needs: determine-job-type
    if: needs.determine-job-type.outputs.job-type == 'job-scan'
    steps:
      - name: Trigger job scanning
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/cron/job-scan"

  cleanup:
    runs-on: ubuntu-latest  
    needs: determine-job-type
    if: needs.determine-job-type.outputs.job-type == 'cleanup'
    steps:
      - name: Trigger cleanup tasks
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/cron/cleanup"

  daily-summary:
    runs-on: ubuntu-latest
    needs: determine-job-type  
    if: needs.determine-job-type.outputs.job-type == 'daily-summary'
    steps:
      - name: Trigger daily summary
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/cron/daily-summary"